import type { EffectTemplate } from "../../app/types";

/**
 * Catalogue de briques mécaniques réutilisables. Les références peuvent
 * surcharger les variables de ces profils sans dupliquer le template.
 */
export const initialEffectTemplates: EffectTemplate[] = [
  {
    id: "effect-ember-burst",
    name: "Décharge de braise",
    description: "Inflige une décharge de feu modulable.",
    tags: ["damage", "fire", "magic"],
    actions: [{ operation: "damage", variables: { value: "1d6 + INT", damageType: "feu" } }],
  },
  {
    id: "effect-frost-bite",
    name: "Morsure de givre",
    description: "Inflige du froid et ralentit la cible.",
    tags: ["damage", "cold", "control"],
    actions: [
      { operation: "damage", variables: { value: "1d6", damageType: "froid" } },
      { operation: "applyCondition", variables: { condition: "slowed", duration: 1 } },
    ],
  },
  {
    id: "effect-lightning-shock",
    name: "Décharge électrique",
    description: "Inflige des dégâts de foudre.",
    tags: ["damage", "lightning", "magic"],
    actions: [{ operation: "damage", variables: { value: "1d8", damageType: "foudre" } }],
  },
  {
    id: "effect-acid-splash",
    name: "Projection acide",
    description: "Inflige des dégâts d'acide à une cible ou dans une petite zone.",
    tags: ["damage", "acid", "alchemy"],
    actions: [{ operation: "damage", variables: { value: "2d6", damageType: "acide" } }],
  },
  {
    id: "effect-venom",
    name: "Venin",
    description: "Blesse et empoisonne une créature vivante.",
    tags: ["damage", "poison", "condition"],
    actions: [
      { operation: "damage", variables: { value: "1d4", damageType: "poison" } },
      { operation: "applyCondition", variables: { condition: "poisoned", duration: 3 } },
    ],
  },
  {
    id: "effect-bleeding-wound",
    name: "Plaie ouverte",
    description: "Inflige une blessure tranchante et applique Saignement.",
    tags: ["damage", "slashing", "condition"],
    actions: [
      { operation: "damage", variables: { value: "1d6", damageType: "tranchant" } },
      { operation: "applyCondition", variables: { condition: "bleeding", duration: 3 } },
    ],
  },
  {
    id: "effect-radiant-strike",
    name: "Frappe radiante",
    description: "Inflige des dégâts radiants.",
    tags: ["damage", "radiant", "divine"],
    actions: [{ operation: "damage", variables: { value: "1d8", damageType: "radiant" } }],
  },
  {
    id: "effect-necrotic-touch",
    name: "Contact nécrotique",
    description: "Draine la vitalité et empêche temporairement les soins.",
    tags: ["damage", "necrotic", "condition"],
    actions: [
      { operation: "damage", variables: { value: "1d6", damageType: "necrotique" } },
      { operation: "applyCondition", variables: { condition: "unhealable", duration: 1 } },
    ],
  },
  {
    id: "effect-thunder-push",
    name: "Onde de choc",
    description: "Inflige du tonnerre et repousse la cible.",
    tags: ["damage", "thunder", "movement"],
    actions: [
      { operation: "damage", variables: { value: "1d6", damageType: "tonnerre" } },
      { operation: "move", variables: { distance: 3, mode: "push" } },
    ],
  },
  {
    id: "effect-psychic-confusion",
    name: "Choc psychique",
    description: "Blesse l'esprit et plonge la cible dans la confusion.",
    tags: ["damage", "psychic", "mind"],
    actions: [
      { operation: "damage", variables: { value: "1d6", damageType: "psychique" } },
      { operation: "applyCondition", variables: { condition: "confused", duration: 1 } },
    ],
  },
  {
    id: "effect-chaotic-bolt",
    name: "Décharge chaotique",
    description: "Inflige un type de dégâts choisi aléatoirement.",
    tags: ["damage", "random", "magic"],
    actions: [{ operation: "randomDamage", variables: { value: "1d8", damageTypes: "feu,froid,foudre,poison" } }],
  },
  {
    id: "effect-minor-healing",
    name: "Soin mineur",
    description: "Rend une petite quantité de PV.",
    tags: ["heal", "recovery"],
    actions: [{ operation: "heal", variables: { value: "1d4 + 1" } }],
  },
  {
    id: "effect-standard-healing",
    name: "Soin",
    description: "Rend une quantité courante de PV.",
    tags: ["heal", "recovery"],
    actions: [{ operation: "heal", variables: { value: "2d4 + 2" } }],
  },
  {
    id: "effect-major-healing",
    name: "Soin majeur",
    description: "Rend une importante quantité de PV.",
    tags: ["heal", "recovery", "powerful"],
    actions: [{ operation: "heal", variables: { value: "4d4 + 4" } }],
  },
  {
    id: "effect-restoration",
    name: "Restauration",
    description: "Retire plusieurs afflictions physiques courantes.",
    tags: ["cleanse", "recovery"],
    actions: [
      { operation: "removeCondition", variables: { condition: "poisoned" } },
      { operation: "removeCondition", variables: { condition: "bleeding" } },
      { operation: "removeCondition", variables: { condition: "burning" } },
    ],
  },
  {
    id: "effect-antidote",
    name: "Antidote",
    description: "Retire l'état Empoisonné.",
    tags: ["cleanse", "poison", "alchemy"],
    actions: [{ operation: "removeCondition", variables: { condition: "poisoned" } }],
  },
  {
    id: "effect-invisibility",
    name: "Invisibilité",
    description: "Masque temporairement la cible aux regards ordinaires.",
    tags: ["stealth", "illusion", "condition"],
    actions: [{ operation: "applyCondition", variables: { condition: "hidden", duration: "10 minutes" } }],
  },
  {
    id: "effect-fear",
    name: "Terreur",
    description: "Applique l'état Effrayé.",
    tags: ["fear", "mind", "condition"],
    actions: [{ operation: "applyCondition", variables: { condition: "frightened", duration: 2 } }],
  },
  {
    id: "effect-charm",
    name: "Charme",
    description: "Applique l'état Charmé.",
    tags: ["charm", "mind", "condition"],
    actions: [{ operation: "applyCondition", variables: { condition: "charmed", duration: 3 } }],
  },
  {
    id: "effect-silence",
    name: "Silence",
    description: "Empêche temporairement la cible de produire les sons nécessaires.",
    tags: ["silence", "control", "condition"],
    actions: [{ operation: "applyCondition", variables: { condition: "silenced", duration: 3 } }],
  },
  {
    id: "effect-knockdown",
    name: "Renversement",
    description: "Met la cible À terre.",
    tags: ["control", "prone", "martial"],
    actions: [{ operation: "applyCondition", variables: { condition: "prone", duration: 1 } }],
  },
  {
    id: "effect-stun",
    name: "Étourdissement",
    description: "Applique l'état Étourdi.",
    tags: ["control", "stun", "condition"],
    actions: [{ operation: "applyCondition", variables: { condition: "stunned", duration: 1 } }],
  },
  {
    id: "effect-restrain",
    name: "Entrave",
    description: "Applique l'état Entravé.",
    tags: ["control", "restraint", "condition"],
    actions: [{ operation: "applyCondition", variables: { condition: "restrained", duration: 2 } }],
  },
  {
    id: "effect-immobilize",
    name: "Immobilisation",
    description: "Empêche temporairement tout déplacement.",
    tags: ["control", "movement", "condition"],
    actions: [{ operation: "applyCondition", variables: { condition: "immobilized", duration: 1 } }],
  },
  {
    id: "effect-slow",
    name: "Ralentissement",
    description: "Applique l'état Ralenti.",
    tags: ["control", "movement", "condition"],
    actions: [{ operation: "applyCondition", variables: { condition: "slowed", duration: 2 } }],
  },
  {
    id: "effect-disarm",
    name: "Désarmement",
    description: "Force la cible à lâcher ce qu'elle tient.",
    tags: ["control", "martial", "condition"],
    actions: [{ operation: "applyCondition", variables: { condition: "disarmed", duration: 1 } }],
  },
  {
    id: "effect-curse",
    name: "Malédiction",
    description: "Applique une malédiction générique qui peut être précisée par la source.",
    tags: ["curse", "magic", "condition"],
    actions: [{ operation: "applyCondition", variables: { condition: "cursed", duration: "jusqu'à dissipation" } }],
  },
  {
    id: "effect-burning",
    name: "Embrasement",
    description: "Enflamme la cible.",
    tags: ["fire", "damage-over-time", "condition"],
    actions: [{ operation: "applyCondition", variables: { condition: "burning", duration: 3 } }],
  },
  {
    id: "effect-mark",
    name: "Marque",
    description: "Désigne une cible pour la poursuite ou une attaque ultérieure.",
    tags: ["mark", "tracking", "condition"],
    actions: [{ operation: "applyCondition", variables: { condition: "marked", duration: 3 } }],
  },
  {
    id: "effect-taunt",
    name: "Provocation",
    description: "Attire l'attention hostile de la cible.",
    tags: ["taunt", "control", "condition"],
    actions: [{ operation: "applyCondition", variables: { condition: "taunted", duration: 1 } }],
  },
  {
    id: "effect-short-teleport",
    name: "Téléportation courte",
    description: "Téléporte le lanceur vers une destination proche.",
    tags: ["movement", "teleport", "magic"],
    actions: [{ operation: "teleport", variables: { range: 3 } }],
  },
  {
    id: "effect-force-push",
    name: "Poussée",
    description: "Repousse une cible de quelques mètres.",
    tags: ["movement", "control"],
    actions: [{ operation: "move", variables: { distance: 3, mode: "push" } }],
  },
  {
    id: "effect-speed-boost",
    name: "Accélération",
    description: "Ajoute du mouvement disponible pour le tour.",
    tags: ["movement", "resource"],
    actions: [{ operation: "modifyResource", variables: { resource: "movement", op: "add", value: 3 } }],
  },
  {
    id: "effect-action-surge",
    name: "Action supplémentaire",
    description: "Rend une action principale.",
    tags: ["action", "resource", "martial"],
    actions: [{ operation: "modifyResource", variables: { resource: "action", op: "add", value: 1 } }],
  },
  {
    id: "effect-reaction-refresh",
    name: "Réflexes renouvelés",
    description: "Rend une réaction.",
    tags: ["reaction", "resource"],
    actions: [{ operation: "modifyResource", variables: { resource: "reaction", op: "add", value: 1 } }],
  },
  {
    id: "effect-fire-ward",
    name: "Protection contre le feu",
    description: "Réduit les dégâts de feu reçus sans les annuler totalement.",
    tags: ["resistance", "fire", "defense"],
    actions: [{ operation: "reduceDamage", variables: { damageType: "feu", value: 2, minDamage: 1 } }],
  },
  {
    id: "effect-cold-ward",
    name: "Protection contre le froid",
    description: "Réduit les dégâts de froid reçus sans les annuler totalement.",
    tags: ["resistance", "cold", "defense"],
    actions: [{ operation: "reduceDamage", variables: { damageType: "froid", value: 2, minDamage: 1 } }],
  },
  {
    id: "effect-poison-ward",
    name: "Protection contre le poison",
    description: "Réduit les dégâts de poison reçus sans les annuler totalement.",
    tags: ["resistance", "poison", "defense"],
    actions: [{ operation: "reduceDamage", variables: { damageType: "poison", value: 2, minDamage: 1 } }],
  },
  {
    id: "effect-binding-curse",
    name: "Lien maudit",
    description: "Empêche de retirer un objet équipé tant que le lien n'est pas brisé.",
    tags: ["curse", "binding", "equipment"],
    actions: [{ operation: "preventUnequip", variables: {} }],
  },
  {
    id: "effect-smoke-cloud",
    name: "Nuage de fumée",
    description: "Crée une zone opaque qui gêne la vision.",
    tags: ["zone", "smoke", "control"],
    actions: [{ operation: "createZone", variables: {
      zoneKind: "darkness", radius: 2, condition: "blinded", trigger: "startTurn",
      name: "Nuage de fumée", description: "Une fumée opaque masque les silhouettes.",
      rule: "La zone gêne fortement la vision.", color: "#5C5566",
    } }],
  },
  {
    id: "effect-burning-ground",
    name: "Sol enflammé",
    description: "Crée une zone qui brûle les créatures qui y pénètrent.",
    tags: ["zone", "fire", "hazard"],
    actions: [{ operation: "createZone", variables: {
      zoneKind: "hazard", radius: 2, damage: "1d6", damageType: "feu", trigger: "enter",
      name: "Sol enflammé", description: "Des flammes courent sur le sol.",
      rule: "Entrer dans la zone inflige des dégâts de feu.", color: "#7A1F2E",
    } }],
  },
  {
    id: "effect-caltrops-field",
    name: "Champ de chausses-trappes",
    description: "Crée une zone de pointes qui blesse et ralentit.",
    tags: ["zone", "trap", "control"],
    actions: [{ operation: "createZone", variables: {
      zoneKind: "hazard", radius: 1, damage: 1, damageType: "perforant", condition: "slowed", trigger: "enter",
      name: "Chausses-trappes", description: "Des pointes métalliques couvrent le sol.",
      rule: "Entrer dans la zone blesse et ralentit.", color: "#7A1F2E",
    } }],
  },
  {
    id: "effect-slippery-ground",
    name: "Sol glissant",
    description: "Crée une zone susceptible de faire chuter.",
    tags: ["zone", "control", "terrain"],
    actions: [{ operation: "createZone", variables: {
      zoneKind: "terrain", radius: 2, condition: "slippery-footing", trigger: "enter",
      name: "Sol glissant", description: "La surface devient difficile à traverser.",
      rule: "Entrer dans la zone applique Sol glissant.", color: "#2F5C7A",
    } }],
  },
  {
    id: "effect-summon-wolf",
    name: "Appel du loup",
    description: "Invoque un loup allié à proximité.",
    tags: ["summon", "beast", "ally"],
    actions: [{ operation: "summon", variables: { enemyTemplateId: "enemy-wolf", count: 1, side: "allies" } }],
  },
  {
    id: "effect-summon-skeleton",
    name: "Relève-squelette",
    description: "Invoque un squelette temporaire.",
    tags: ["summon", "undead", "magic"],
    actions: [{ operation: "summon", variables: { enemyTemplateId: "enemy-skeleton", count: 1, side: "allies" } }],
  },
  {
    id: "effect-dispel-curse",
    name: "Briser la malédiction",
    description: "Retire une malédiction générique.",
    tags: ["dispel", "curse", "cleanse"],
    actions: [{ operation: "dispel", variables: { condition: "cursed" } }],
  },
  {
    id: "effect-dispel-zone",
    name: "Dissiper une zone",
    description: "Retire une zone de ténèbres ou de fumée.",
    tags: ["dispel", "zone", "magic"],
    actions: [{ operation: "dispel", variables: { zoneKind: "darkness" } }],
  },
  {
    id: "effect-grant-ember-bolt",
    name: "Accorder Trait de braise",
    description: "Accorde la capacité Trait de braise tant que la source reste active.",
    tags: ["grant", "ability", "fire"],
    actions: [{ operation: "grantAbility", variables: { abilityTemplateId: "abl_ember_bolt" } }],
  },
  {
    id: "effect-grant-shadow-step",
    name: "Accorder Pas d'ombre",
    description: "Accorde la capacité Pas d'ombre tant que la source reste active.",
    tags: ["grant", "ability", "shadow"],
    actions: [{ operation: "grantAbility", variables: { abilityTemplateId: "abl_shadow_step" } }],
  },
  {
    id: "effect-brew-healing-potion",
    name: "Préparation de potion",
    description: "Transforme une plante sauvage en potion de soin.",
    tags: ["inventory", "craft", "alchemy"],
    actions: [{ operation: "inventoryInteraction", variables: {
      requiredTemplateId: "tpl_wild_plant", consumeRequired: true,
      addTemplateId: "tpl_healing_potion", quantity: 1,
    } }],
  },
  {
    id: "effect-cure-silence",
    name: "Rendre la voix",
    description: "Retire l'état Silencieux.",
    tags: ["cleanse", "silence", "recovery"],
    actions: [{ operation: "removeCondition", variables: { condition: "silenced" } }],
  },
];
