import type { CombatConditionTemplate } from "../../app/types";

const normalizeConditionKey = (value: string) =>
  value
    .trim()
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");

export const initialCombatConditionTemplates: CombatConditionTemplate[] = [
  {
    id: "prone",
    name: "À terre",
    kind: "harmful",
    description: "La cible est au sol et doit se relever pour agir normalement.",
    aliases: ["a terre", "prone"],
    color: "#B5612A",
    icon: "↧",
    tags: ["movement", "melee"],
    rules: ["Se relever coûte une action de mouvement."],
  },
  {
    id: "poisoned",
    name: "Empoisonné",
    kind: "harmful",
    description: "La cible subit un poison actif.",
    aliases: ["empoisonne", "poison"],
    color: "#6B4A5C",
    icon: "✕",
    tags: ["poison", "body"],
    rules: ["Peut infliger des dégâts ou un malus selon la source."],
  },
  {
    id: "frightened",
    name: "Effrayé",
    kind: "harmful",
    description: "La cible hésite face à une menace.",
    aliases: ["effraye", "peur"],
    color: "#5A2233",
    icon: "!",
    tags: ["mind", "fear"],
    rules: ["Peut limiter l'approche ou imposer un malus narratif."],
  },
  {
    id: "restrained",
    name: "Entravé",
    kind: "harmful",
    description: "La cible est retenue ou gênée dans ses mouvements.",
    aliases: ["entrave", "retenu"],
    color: "#7A1F2E",
    icon: "≡",
    tags: ["movement", "control"],
    rules: ["La vitesse peut tomber à 0 selon la source."],
  },
  {
    id: "blinded",
    name: "Aveuglé",
    kind: "harmful",
    description: "La cible ne voit plus correctement.",
    aliases: ["aveugle"],
    color: "#5C5566",
    icon: "○",
    tags: ["senses"],
    rules: ["Les actions qui exigent la vue deviennent difficiles ou impossibles."],
  },
  {
    id: "stunned",
    name: "Étourdi",
    kind: "harmful",
    description: "La cible peine à agir ou à réagir.",
    aliases: ["etourdi", "sonné", "sonne"],
    color: "#8C3F73",
    icon: "✦",
    tags: ["control", "mind"],
    rules: ["Peut retirer l'action ou la réaction selon la source."],
  },
  {
    id: "confused",
    name: "Confus",
    kind: "harmful",
    description: "La cible distingue mal alliés, ennemis et priorités.",
    aliases: ["confusion", "désorienté", "desoriente"],
    color: "#8C3F73",
    icon: "?",
    tags: ["mind", "control", "random"],
    rules: ["Peut forcer une cible aléatoire, une action hésitante ou une perte d'action selon la source."],
  },
  {
    id: "charmed",
    name: "Charmé",
    kind: "harmful",
    description: "La cible est influencée par une autre créature.",
    aliases: ["charme", "séduit", "seduit"],
    color: "#C7007E",
    icon: "◇",
    tags: ["mind", "control", "social"],
    rules: ["La cible peut refuser d'attaquer l'origine du charme ou lui faire confiance."],
  },
  {
    id: "silenced",
    name: "Silencieux",
    kind: "harmful",
    description: "La cible ne peut plus produire ou utiliser certains sons.",
    aliases: ["silence", "muet", "bâillonné", "baillonne"],
    color: "#4B3B66",
    icon: "∅",
    tags: ["magic", "sound", "casting"],
    rules: ["Peut empêcher les capacités verbales, appels, ordres ou incantations."],
  },
  {
    id: "unhealable",
    name: "Insoignable",
    kind: "harmful",
    description: "La cible ne peut pas récupérer de PV par les soins normaux.",
    aliases: ["anti-soin", "anti soin", "soin impossible", "impossible à soigner", "impossible a soigner"],
    color: "#661309",
    icon: "×",
    tags: ["body", "healing", "curse"],
    rules: ["Les effets de soin doivent échouer ou être réduits tant que l'état persiste."],
  },
  {
    id: "vulnerable",
    name: "Vulnérable",
    kind: "harmful",
    description: "La cible encaisse plus durement un certain type d'attaque.",
    aliases: ["vulnerable", "fragilisé", "fragilise"],
    color: "#B5612A",
    icon: "▽",
    tags: ["damage", "debuff"],
    rules: ["Le type de vulnérabilité doit être précisé par la source ou un tag."],
  },
  {
    id: "weakened",
    name: "Affaibli",
    kind: "harmful",
    description: "La cible perd en puissance physique ou offensive.",
    aliases: ["affaiblie", "faiblesse"],
    color: "#6E5A3C",
    icon: "−",
    tags: ["body", "damage", "debuff"],
    rules: ["Peut réduire les dégâts, les jets de Force ou les attaques selon la source."],
  },
  {
    id: "marked",
    name: "Marqué",
    kind: "harmful",
    description: "La cible est désignée par une menace, une malédiction ou un chasseur.",
    aliases: ["marque", "ciblé", "cible"],
    color: "#9C7A2E",
    icon: "◎",
    tags: ["tracking", "targeting", "curse"],
    rules: ["Peut faciliter le ciblage, la poursuite ou certains dégâts bonus."],
  },
  {
    id: "taunted",
    name: "Provoqué",
    kind: "harmful",
    description: "La cible est poussée à concentrer son attention sur une menace.",
    aliases: ["provoque", "défié", "defie"],
    color: "#7A1F2E",
    icon: "!",
    tags: ["mind", "control", "aggro"],
    rules: ["Peut orienter les attaques vers la source de la provocation."],
  },
  {
    id: "deafened",
    name: "Assourdi",
    kind: "harmful",
    description: "La cible entend mal ou plus du tout.",
    aliases: ["sourd", "surdité", "surdite"],
    color: "#5C5566",
    icon: "∿",
    tags: ["senses", "sound"],
    rules: ["Les perceptions sonores, ordres et alertes peuvent échouer."],
  },
  {
    id: "immobilized",
    name: "Immobilisé",
    kind: "harmful",
    description: "La cible ne peut pas se déplacer, même si elle peut encore agir.",
    aliases: ["immobilise", "cloué", "cloue"],
    color: "#7A1F2E",
    icon: "⊓",
    tags: ["movement", "control"],
    rules: ["La vitesse tombe généralement à 0, sans forcément empêcher les actions."],
  },
  {
    id: "disarmed",
    name: "Désarmé",
    kind: "harmful",
    description: "La cible a perdu l'usage immédiat d'une arme ou d'un objet tenu.",
    aliases: ["desarme", "arme perdue"],
    color: "#6E5A3C",
    icon: "/",
    tags: ["equipment", "weapon"],
    rules: ["Empêche ou limite les attaques qui exigent l'objet perdu."],
  },
  {
    id: "burned-out",
    name: "À bout",
    kind: "harmful",
    description: "La cible a épuisé une ressource mentale, magique ou physique importante.",
    aliases: ["a bout", "vidé", "vide", "épuisement magique", "epuisement magique"],
    color: "#4B3B66",
    icon: "□",
    tags: ["resource", "fatigue", "magic"],
    rules: ["Peut bloquer une capacité ou une recharge jusqu'au repos."],
  },
  {
    id: "slowed",
    name: "Ralenti",
    kind: "harmful",
    description: "La cible se déplace moins efficacement.",
    color: "#3F6C8A",
    icon: "↘",
    tags: ["movement"],
    rules: ["Réduit la distance de déplacement disponible."],
  },
  {
    id: "submerged",
    name: "Submergé",
    kind: "harmful",
    description: "La cible est engloutie, immergée ou prise dans une masse qui gêne fortement ses mouvements.",
    aliases: ["submerge", "englouti", "immerge", "immergé", "noyé", "noye"],
    color: "#2F5C7A",
    icon: "≈",
    tags: ["terrain", "water", "movement", "control"],
    rules: ["Peut arrêter le mouvement, gêner les actions et imposer des tests pour se dégager selon la source."],
  },
  {
    id: "bleeding",
    name: "Saignement",
    kind: "harmful",
    description: "La cible perd du sang.",
    color: "#7A1F2E",
    icon: "+",
    tags: ["body", "damage"],
    rules: ["Peut infliger des dégâts récurrents selon la source."],
  },
  {
    id: "burning",
    name: "Brûlure",
    kind: "harmful",
    description: "La cible souffre d'une brûlure active.",
    aliases: ["brulure", "en feu"],
    color: "#B5612A",
    icon: "△",
    tags: ["fire", "damage"],
    rules: ["Peut infliger des dégâts de feu récurrents."],
  },
  {
    id: "exhausted",
    name: "Épuisé",
    kind: "harmful",
    description: "La cible est à bout de forces.",
    aliases: ["epuise", "fatigue"],
    color: "#6E5A3C",
    icon: "−",
    tags: ["body"],
    rules: ["Peut réduire les performances jusqu'au repos."],
  },
  {
    id: "cursed",
    name: "Maudit",
    kind: "harmful",
    description: "La cible subit une influence magique néfaste.",
    color: "#4B3B66",
    icon: "◇",
    tags: ["magic", "curse"],
    rules: ["Les effets exacts dépendent de la malédiction."],
  },
  {
    id: "unconscious",
    name: "Inconscient",
    kind: "harmful",
    description: "La cible ne peut plus agir.",
    aliases: ["hors de combat", "hors d'état de nuire", "hors d'etat de nuire"],
    color: "#5C5566",
    icon: "×",
    tags: ["body", "incapacitated"],
    rules: ["La cible ne joue pas son tour tant qu'elle reste inconsciente."],
  },
  {
    id: "slippery-footing",
    name: "Appuis glissants",
    kind: "harmful",
    description: "Le sol rend les déplacements dangereux.",
    color: "#3F6C8A",
    icon: "≈",
    tags: ["terrain", "movement"],
    rules: ["Peut provoquer une chute ou gêner le déplacement."],
  },
  {
    id: "fragile-balance",
    name: "Équilibre fragile",
    kind: "harmful",
    description: "La cible risque de perdre pied.",
    aliases: ["equilibre fragile"],
    color: "#3F6C8A",
    icon: "↯",
    tags: ["terrain", "movement"],
    rules: ["Peut imposer un test ou gêner le déplacement."],
  },
  {
    id: "hidden",
    name: "Dissimulé",
    kind: "beneficial",
    description: "La cible est plus difficile à percevoir.",
    aliases: ["caché", "cache", "invisible", "dans l'ombre"],
    color: "#4B3B66",
    icon: "◌",
    tags: ["stealth"],
  },
  {
    id: "high-ground",
    name: "Position dominante",
    kind: "beneficial",
    description: "La cible bénéficie d'une meilleure position.",
    color: "#9C7A2E",
    icon: "△",
    tags: ["terrain", "advantage"],
  },
  {
    id: "alert",
    name: "Alerte",
    kind: "neutral",
    description: "La cible a été avertie d'un danger.",
    color: "#9C7A2E",
    icon: "!",
    tags: ["awareness"],
  },
];

const combatConditionLookup = new Map<string, CombatConditionTemplate>();

initialCombatConditionTemplates.forEach((condition) => {
  [condition.id, condition.name, ...(condition.aliases ?? [])].forEach((alias) => {
    combatConditionLookup.set(normalizeConditionKey(alias), condition);
  });
});

export function getCombatConditionTemplate(condition: string): CombatConditionTemplate | null {
  return combatConditionLookup.get(normalizeConditionKey(condition)) ?? null;
}

export function isHarmfulCombatCondition(condition: string): boolean {
  return getCombatConditionTemplate(condition)?.kind === "harmful";
}
