import type { ItemTemplate } from "../../app/types";
import { itemEffects } from "./itemEffects";

export const initialItemTemplates: ItemTemplate[] = [
  {
    id: "tpl_shortbow",
    type: "weapon",
    types: ["weapon"],
    tags: ["weapon", "wood", "ranged", "mundane", "ammunition", "two-handed"],
    name: "Arc court",
    description: "Un arc léger et fiable, facile à adapter aux traditions d'une région ou d'une compagnie.",
    rarity: "mundane",
    base: {
      range: 24,
      damage: "1d6",
      damageType: "perforant",
      weight: 0.9,
    },
    attacks: [
      {
        id: "shot",
        name: "Tir",
        label: "Tirer",
        range: 24,
        damage: "1d6",
        damageType: "perforant",
        attackKind: "ranged",
      },
    ],
    effects: [],
    targetingV2: {
      aim: { allowed: ["entity", "position"], required: true, range: 24, lineOfSight: true },
      area: { shape: "none" },
      affects: { allowed: ["living"], maxTargets: 1, requiresLiving: true },
      defaultPriority: ["nearestEnemy"],
      suggestedSides: ["enemy"],
    },
    modules: {
      item: {},
    },
  },
  {
    id: "tpl_dagger",
    type: "weapon",
    types: ["weapon"],
    tags: ["weapon", "metal", "dagger", "mundane", "finesse", "light", "thrown"],
    aliases: ["couteau", "lame courte"],
    name: "Dague",
    description: "Une lame courte et polyvalente, efficace en main comme au lancer.",
    rarity: "mundane",
    base: { range: 1.5, damage: "1d4", damageType: "perforant", weight: 0.45 },
    effects: [],
    attacks: [
      { id: "stab", name: "Coup de dague", label: "Frapper", range: 1.5, damage: "1d4", damageType: "perforant", attackKind: "melee" },
      { id: "throw", name: "Lancer", label: "Lancer", range: 6, damage: "1d4", damageType: "perforant", attackKind: "ranged" },
    ],
    targetingV2: {
      aim: { allowed: ["entity", "position"], required: true, range: 6, lineOfSight: true },
      area: { shape: "none" },
      affects: { allowed: ["living"], maxTargets: 1, requiresLiving: true },
      defaultPriority: ["nearestEnemy"],
      suggestedSides: ["enemy"],
    },
    modules: { item: {} },
  },
  {
    id: "tpl_quarterstaff",
    type: "weapon",
    types: ["weapon"],
    tags: ["weapon", "wood", "staff", "mundane", "versatile"],
    aliases: ["bâton", "baton", "bâton de marche"],
    name: "Bâton",
    description: "Un solide bâton de marche pouvant être manié à une ou deux mains.",
    rarity: "mundane",
    base: { range: 1.5, damage: "1d6", damageType: "contondant", weight: 1.8 },
    effects: [],
    attacks: [
      { id: "strike", name: "Frappe", label: "Frapper", range: 1.5, damage: "1d6", damageType: "contondant", attackKind: "melee" },
      { id: "two-handed-strike", name: "Frappe à deux mains", label: "Frapper à deux mains", range: 1.5, damage: "1d8", damageType: "contondant", attackKind: "melee" },
    ],
    targetingV2: {
      aim: { allowed: ["entity", "position"], required: true, range: 1.5, lineOfSight: true },
      area: { shape: "none" },
      affects: { allowed: ["living"], maxTargets: 1, requiresLiving: true },
      defaultPriority: ["nearestEnemy"],
      suggestedSides: ["enemy"],
    },
    modules: { item: {} },
  },
  {
    id: "tpl_spear",
    type: "weapon",
    types: ["weapon"],
    tags: ["weapon", "wood", "metal", "spear", "mundane", "versatile", "thrown"],
    aliases: ["lance courte", "épieu", "epieu"],
    name: "Lance",
    description: "Une arme simple qui garde l'adversaire à distance et peut être lancée.",
    rarity: "mundane",
    base: { range: 1.5, damage: "1d6", damageType: "perforant", weight: 1.4 },
    effects: [],
    attacks: [
      { id: "thrust", name: "Estoc", label: "Frapper", range: 1.5, damage: "1d6", damageType: "perforant", attackKind: "melee" },
      { id: "two-handed-thrust", name: "Estoc à deux mains", label: "Frapper à deux mains", range: 1.5, damage: "1d8", damageType: "perforant", attackKind: "melee" },
      { id: "throw", name: "Lancer", label: "Lancer", range: 6, damage: "1d6", damageType: "perforant", attackKind: "ranged" },
    ],
    targetingV2: {
      aim: { allowed: ["entity", "position"], required: true, range: 6, lineOfSight: true },
      area: { shape: "none" },
      affects: { allowed: ["living"], maxTargets: 1, requiresLiving: true },
      defaultPriority: ["nearestEnemy"],
      suggestedSides: ["enemy"],
    },
    modules: { item: {} },
  },
  {
    id: "tpl_longsword",
    type: "weapon",
    types: ["weapon"],
    tags: ["weapon", "metal", "sword", "mundane", "versatile"],
    aliases: ["épée", "epee", "épée longue"],
    name: "Épée longue",
    description: "Une arme martiale équilibrée, utilisable avec une ou deux mains.",
    rarity: "mundane",
    base: { range: 1.5, damage: "1d8", damageType: "tranchant", weight: 1.4 },
    effects: [],
    attacks: [
      { id: "slash", name: "Taille", label: "Frapper", range: 1.5, damage: "1d8", damageType: "tranchant", attackKind: "melee" },
      { id: "two-handed-slash", name: "Taille à deux mains", label: "Frapper à deux mains", range: 1.5, damage: "1d10", damageType: "tranchant", attackKind: "melee" },
    ],
    targetingV2: {
      aim: { allowed: ["entity", "position"], required: true, range: 1.5, lineOfSight: true },
      area: { shape: "none" },
      affects: { allowed: ["living"], maxTargets: 1, requiresLiving: true },
      defaultPriority: ["nearestEnemy"],
      suggestedSides: ["enemy"],
    },
    modules: { item: {} },
  },
  {
    id: "tpl_light_crossbow",
    type: "weapon",
    types: ["weapon"],
    tags: ["weapon", "wood", "metal", "crossbow", "mundane", "ranged", "ammunition", "loading", "two-handed"],
    aliases: ["arbalète", "arbalete"],
    name: "Arbalète légère",
    description: "Une arme à distance puissante mais lente à recharger.",
    rarity: "mundane",
    base: { range: 24, damage: "1d8", damageType: "perforant", weight: 2.3 },
    effects: [],
    attacks: [
      { id: "bolt", name: "Carreau", label: "Tirer", range: 24, damage: "1d8", damageType: "perforant", attackKind: "ranged" },
    ],
    targetingV2: {
      aim: { allowed: ["entity", "position"], required: true, range: 24, lineOfSight: true },
      area: { shape: "none" },
      affects: { allowed: ["living"], maxTargets: 1, requiresLiving: true },
      defaultPriority: ["nearestEnemy"],
      suggestedSides: ["enemy"],
    },
    modules: { item: {} },
  },
  {
    id: "tpl_leather_armor",
    type: "armor",
    types: ["armor"],
    tags: ["armor", "leather", "light", "mundane"],
    name: "Armure de cuir",
    description: "Une protection légère qui conserve toute la mobilité de son porteur.",
    rarity: "mundane",
    base: { defenseBase: 11, maxDexBonus: 99, weight: 4.5 },
    effects: [],
    modules: { item: {} },
  },
  {
    id: "tpl_chain_mail",
    type: "armor",
    types: ["armor"],
    tags: ["armor", "metal", "heavy", "mundane"],
    aliases: ["cotte de mailles"],
    name: "Cotte de mailles",
    description: "Une lourde protection d'anneaux entrelacés qui privilégie la solidité à l'agilité.",
    rarity: "mundane",
    base: { defenseBase: 16, minDexBonus: 0, maxDexBonus: 0, minimumStrength: 13, weight: 25 },
    effects: [],
    modules: { item: {} },
  },
  {
    id: "tpl_shield",
    type: "armor",
    types: ["armor"],
    tags: ["armor", "shield", "wood", "metal", "mundane"],
    aliases: ["écu", "ecu", "bouclier"],
    name: "Bouclier",
    description: "Une protection tenue en main qui accorde +2 en Défense sans se cumuler avec un autre bouclier.",
    rarity: "mundane",
    base: { defenseBonus: 2, weight: 2.7 },
    effects: [],
    modules: { item: {} },
  },
  {
    id: "tpl_backpack",
    type: "container",
    types: ["misc"],
    tags: ["container", "cloth", "leather", "travel", "mundane"],
    aliases: ["sac", "sac à dos"],
    name: "Sac à dos",
    description: "Un sac robuste pour organiser et transporter le nécessaire d'une expédition.",
    rarity: "mundane",
    base: { weight: 2.3 },
    effects: [],
    modules: { item: {}, container: { capacityWeight: 15 } },
  },
  {
    id: "tpl_rope",
    type: "tool",
    types: ["misc"],
    tags: ["tool", "hemp", "travel", "climbing", "mundane"],
    aliases: ["corde de chanvre", "cordage"],
    name: "Corde",
    description: "Quinze mètres de corde solide, utile pour grimper, attacher ou improviser.",
    rarity: "mundane",
    base: { length: 15, weight: 4.5 },
    effects: [],
    modules: { item: {} },
  },
  {
    id: "tpl_thieves_tools",
    type: "tool",
    types: ["misc"],
    tags: ["tool", "metal", "lock", "trap", "mundane"],
    aliases: ["outils de voleur", "crochets", "rossignols"],
    name: "Outils de voleur",
    description: "Un étui de crochets, pinces et petites limes pour travailler sur serrures et pièges.",
    rarity: "mundane",
    base: { weight: 0.45 },
    effects: [],
    modules: { item: {} },
  },
  {
    id: "tpl_acid_vial",
    type: "consumable",
    types: ["consumable"],
    tags: ["consumable", "acid", "vial", "glass", "alchemy", "thrown"],
    name: "Fiole d'acide",
    description: "Une fiole jetable qui inflige 2d6 dégâts d'acide dans une zone très réduite.",
    rarity: "common",
    base: { weight: 0.45 },
    effects: [itemEffects.acidVial],
    targetingV2: {
      aim: { allowed: ["entity", "position"], required: true, range: 6, lineOfSight: true },
      area: { shape: "circle", radius: 0.5 },
      affects: { allowed: ["living", "object"], requiresLiving: false },
      defaultPriority: ["nearestEnemy"],
      suggestedSides: ["enemy"],
    },
    modules: { item: {} },
  },
  {
    id: "tpl_antitoxin",
    type: "consumable",
    types: ["consumable"],
    tags: ["consumable", "potion", "alchemy", "antidote", "glass"],
    aliases: ["antidote"],
    name: "Antitoxine",
    description: "Une dose alchimique qui retire l'état Empoisonné.",
    rarity: "common",
    base: { weight: 0.1 },
    effects: [itemEffects.removePoisoned],
    targetingV2: {
      aim: { allowed: ["self", "entity"], required: true, range: 1.5, lineOfSight: true },
      area: { shape: "none" },
      affects: { allowed: ["self", "living"], maxTargets: 1, requiresLiving: true },
      defaultPriority: ["self"],
      suggestedSides: ["self", "ally"],
    },
    modules: { item: {} },
  },
  {
    id: "tpl_caltrops",
    type: "consumable",
    types: ["consumable"],
    tags: ["consumable", "metal", "trap", "caltrops", "mundane"],
    aliases: ["chausses-trappes", "pointes"],
    name: "Chausses-trappes",
    description: "Une poignée de pointes à répandre au sol pour ralentir un passage.",
    rarity: "mundane",
    base: { weight: 0.9 },
    effects: [itemEffects.caltropsZone],
    targetingV2: {
      aim: { allowed: ["position"], required: true, range: 3, lineOfSight: true },
      area: { shape: "circle", radius: 1 },
      affects: { allowed: ["position"] },
      defaultPriority: ["farthestPointAhead"],
    },
    modules: { item: {} },
  },
  {
    id: "tpl_smoke_bomb",
    type: "consumable",
    types: ["consumable"],
    tags: ["consumable", "alchemy", "smoke", "thrown", "utility"],
    aliases: ["fumigène", "fumigene"],
    name: "Fumigène",
    description: "Une capsule qui déploie un nuage opaque de deux mètres de rayon.",
    rarity: "common",
    base: { weight: 0.2 },
    effects: [itemEffects.smokeZone],
    targetingV2: {
      aim: { allowed: ["position"], required: true, range: 6, lineOfSight: true },
      area: { shape: "circle", radius: 2 },
      affects: { allowed: ["position"] },
      defaultPriority: ["farthestPointAhead"],
    },
    modules: { item: {} },
  },
  {
    id: "tpl_rations",
    type: "consumable",
    types: ["food", "consumable"],
    tags: ["food", "consumable", "travel", "dry"],
    name: "Rations",
    description: "Vivres de route, secs mais rassurants.",
    rarity: "mundane",
    base: {
      weight: 0.5,
    },
    effects: [],
    modules: {
      item: {},
    },
  },
  {
    id: "tpl_healing_potion",
    type: "consumable",
    types: ["consumable"],
    tags: ["consumable", "potion", "alchemy", "healing", "glass"],
    name: "Potion de soin",
    description: "Une préparation alchimique commune qui rend 2d4 + 2 PV.",
    rarity: "common",
    base: {
      weight: 0.25,
    },
    effects: [itemEffects.healingPotion],
    targetingV2: {
      aim: { allowed: ["self", "entity"], required: true, lineOfSight: true },
      area: { shape: "none" },
      affects: { allowed: ["self", "living"], maxTargets: 1, requiresLiving: true },
      defaultPriority: ["self"],
      suggestedSides: ["self", "ally"],
    },
    targeting: {
      allowed: ["self", "character"],
      required: true,
      defaultPriority: ["self"],
    },
    modules: {
      item: {},
    },
  },
  {
    id: "tpl_heavy_arrows",
    type: "consumable",
    types: ["consumable", "ammunition"],
    tags: ["consumable", "ammunition", "arrow", "metal", "heavy"],
    name: "Flèches lourdes",
    description: "Des flèches épaisses, faites pour frapper fort au prix d'une trajectoire plus courte.",
    rarity: "mundane",
    base: {
      weight: 0.08,
    },
    effects: [],
    attackModifiers: [
      {
        id: "heavy-arrow-shot",
        name: "Flèche lourde",
        appliesToTags: ["ranged"],
        appliesToAttackKinds: ["ranged"],
        rangeModifier: -6,
        damageModifier: "1d4",
        damageType: "perforant",
        consumeOnUse: true,
      },
    ],
    modules: {
      item: {},
    },
  },
  {
    id: "tpl_poison_vial",
    type: "consumable",
    types: ["consumable"],
    tags: ["consumable", "poison", "vial", "glass", "alchemy"],
    name: "Fiole de poison",
    description: "Un venin noirâtre. Dangereux si on l'utilise sans précaution.",
    rarity: "common",
    base: {
      weight: 0.1,
    },
    effects: [itemEffects.damagePoison2],
    targetingV2: {
      aim: { allowed: ["self", "entity", "position"], required: true, range: 6, lineOfSight: true },
      area: { shape: "none" },
      affects: { allowed: ["living"], maxTargets: 1, requiresLiving: true },
      defaultPriority: ["nearestEnemy"],
      suggestedSides: ["enemy"],
    },
    targeting: {
      allowed: ["entity", "character", "free"],
      required: true,
      defaultPriority: ["nearestEnemy"],
      range: 18,
    },
    modules: {
      item: {},
    },
  },
  {
    id: "tpl_shadow_cloak",
    type: "garment",
    types: ["accessory"],
    tags: ["accessory", "garment", "cloth", "shadow", "magic"],
    name: "Cape d'ombre",
    description: "Un tissu enchanté qui permet à son porteur de franchir brièvement une ombre.",
    rarity: "rare",
    requiresAttunement: true,
    base: {
      weight: 1.2,
    },
    effects: [itemEffects.grantShadowStep],
    modules: {
      item: {},
    },
  },
  {
    id: "tpl_eternal_bond_boots",
    type: "garment",
    types: ["accessory"],
    tags: ["accessory", "boots", "leather", "cursed", "magic", "bound"],
    name: "Bottes du lien éternel",
    description: "Des bottes de cuir noir qui refusent de quitter les pieds de leur porteur.",
    rarity: "rare",
    requiresAttunement: true,
    base: {
      weight: 1.1,
    },
    effects: [
      itemEffects.preventUnequip,
    ],
    modules: {
      item: {
        effectsState: "known",
      },
    },
  },
  {
    id: "tpl_nameless_ring",
    type: "garment",
    types: ["accessory"],
    tags: ["accessory", "ring", "silver", "unknown", "magic", "rare", "attunement"],
    name: "Anneau des serments oubliés",
    description: "Un anneau d'argent gravé de noms que la mémoire refuse de retenir.",
    rarity: "rare",
    requiresAttunement: true,
    base: {
      weight: 0.05,
    },
    effects: [itemEffects.rareCharismaPlus2],
    modules: {
      item: {
        nameState: "unknown",
        unknownName: "Anneau inconnu",
        effectsState: "unknown",
      },
    },
  },
  {
    id: "tpl_blank_scroll",
    type: "consumable",
    types: ["quest", "consumable"],
    tags: ["quest", "consumable", "scroll", "paper", "magic", "silence"],
    name: "Parchemin de silence",
    description: "Le texte n'apparait que lorsque personne ne le regarde.",
    rarity: "uncommon",
    base: {
      weight: 0.1,
    },
    effects: [itemEffects.silence],
    targetingV2: {
      aim: { allowed: ["self", "entity", "position"], required: true, range: 9, lineOfSight: true },
      area: { shape: "circle", radius: 3 },
      affects: { allowed: ["living"], requiresLiving: true },
      defaultPriority: ["self"],
      suggestedSides: ["self", "ally"],
    },
    targeting: {
      allowed: ["self", "character", "entity", "position", "free"],
      required: true,
      defaultPriority: ["self"],
    },
    modules: {
      item: {
        descriptionState: "hidden",
        effectsState: "hidden",
      },
    },
  },
  {
    id: "tpl_cracked_armor",
    type: "armor",
    types: ["armor"],
    tags: ["armor", "metal", "damaged", "cracked", "heavy"],
    name: "Armure fendue",
    description: "Une cotte de mailles endommagée : encombrante, mais encore capable d'arrêter un coup.",
    rarity: "mundane",
    base: {
      defenseBase: 14,
      minDexBonus: 0,
      maxDexBonus: 0,
      weight: 8,
    },
    effects: [],
    modules: {
      item: {},
    },
  },
  {
    id: "tpl_singing_coin",
    type: "trinket",
    types: ["quest"],
    tags: ["quest", "coin", "metal", "ancient", "magic", "key"],
    name: "Obole chantante",
    description: "Une monnaie antique qui fredonne près des portes scellées.",
    rarity: "uncommon",
    base: {
      weight: 0.01,
    },
    effects: [],
    modules: {
      item: {
        nameState: "unknown",
        unknownName: "Pièce ancienne",
        descriptionState: "unknown",
        unknownDescription: "Son usage exact reste à découvrir.",
      },
    },
  },
  {
    id: "tpl_giant_mushroom",
    type: "consumable",
    types: ["food", "consumable"],
    tags: ["food", "consumable", "plant", "mushroom", "unstable"],
    name: "Champignon géant",
    description: "Une bouchée nourrit, deux bouchées inquiètent.",
    rarity: "common",
    base: {
      weight: 0.8,
    },
    effects: itemEffects.damageMixed1,
    targetingV2: {
      aim: { allowed: ["self", "entity"], required: true, lineOfSight: true },
      area: { shape: "none" },
      affects: { allowed: ["self", "living"], maxTargets: 1, requiresLiving: true },
      defaultPriority: ["self"],
      suggestedSides: ["self", "ally"],
    },
    targeting: {
      allowed: ["self", "character"],
      required: true,
      defaultPriority: ["self"],
    },
    modules: {
      item: {
        effectsState: "unknown",
      },
    },
  },
  {
    id: "tpl_magnet_stone",
    type: "material",
    types: ["material"],
    tags: ["material", "stone", "magnetic", "ore", "craft"],
    name: "Pierre d'aimant",
    description: "Un minerai qui tire doucement les clous, les aiguilles et les mauvaises idées.",
    rarity: "mundane",
    base: {
      weight: 2,
    },
    effects: [],
    modules: {
      item: {},
    },
  },
  {
    id: "tpl_field_stone",
    type: "material",
    types: ["material"],
    tags: ["material", "stone", "mundane", "throwable"],
    aliases: ["pierre", "cailloux", "petite pierre"],
    name: "Caillou",
    description: "Une pierre ordinaire, assez petite pour tenir dans la main.",
    rarity: "mundane",
    base: {
      weight: 0.25,
    },
    effects: [],
    modules: {
      item: {},
    },
  },
  {
    id: "tpl_glass_dagger",
    type: "weapon",
    types: ["weapon"],
    tags: ["weapon", "glass", "fragile", "dagger", "sharp", "light"],
    name: "Dague de verre",
    description: "Une lame presque invisible, très vive, très fragile.",
    rarity: "uncommon",
    base: {
      range: 1.5,
      damage: "1d4",
      damageType: "perforant",
      weight: 0.4,
    },
    attacks: [
      {
        id: "stab",
        name: "Coup de dague",
        label: "Frapper",
        range: 1.5,
        damage: "1d4",
        damageType: "perforant",
        attackKind: "melee",
      },
      {
        id: "throw",
        name: "Lancer la dague",
        label: "Lancer",
        range: 6,
        damage: "1d4",
        damageType: "perforant",
        attackKind: "ranged",
      },
    ],
    effects: [],
    targetingV2: {
      aim: { allowed: ["entity", "position"], required: true, range: 1.5, lineOfSight: true },
      area: { shape: "none" },
      affects: { allowed: ["living"], maxTargets: 1, requiresLiving: true },
      defaultPriority: ["nearestEnemy"],
      suggestedSides: ["enemy"],
    },
    modules: {
      item: {
        effectsState: "unknown",
      },
    },
  },
  {
    id: "tpl_mirror_mask",
    type: "garment",
    types: ["accessory"],
    tags: ["accessory", "mask", "mirror", "magic", "deceptive"],
    name: "Masque miroir",
    description: "Il montre aux autres ce qu'ils esperaient voir.",
    rarity: "uncommon",
    requiresAttunement: true,
    base: {
      weight: 0.3,
    },
    effects: [],
    modules: {
      item: {
        descriptionState: "unknown",
        unknownDescription: "Le reflet ne dit pas encore toute la vérité.",
      },
    },
  },
  {
    id: "tpl_cursed_chalice",
    type: "consumable",
    types: ["quest", "consumable"],
    tags: ["quest", "consumable", "chalice", "cursed", "metal", "magic"],
    name: "Calice des dettes",
    description: "Boire au calice accorde un répit, puis réclame son dû.",
    rarity: "rare",
    base: {
      weight: 0.6,
    },
    effects: [itemEffects.heal3, itemEffects.damagePoison2],
    targetingV2: {
      aim: { allowed: ["self", "entity"], required: true, lineOfSight: true },
      area: { shape: "none" },
      affects: { allowed: ["self", "living"], maxTargets: 1, requiresLiving: true },
      defaultPriority: ["self"],
      suggestedSides: ["self", "ally"],
    },
    targeting: {
      allowed: ["self", "character"],
      required: true,
      defaultPriority: ["self"],
    },
    modules: {
      item: {
        nameState: "unknown",
        unknownName: "Calice terni",
        effectsState: "hidden",
      },
    },
  },
  {
    id: "tpl_fireball_scroll",
    type: "consumable",
    types: ["quest", "consumable"],
    tags: ["quest", "consumable", "scroll", "paper", "magic", "fire"],
    name: "Parchemin de boule de feu",
    description: "Une incantation de niveau 3 scellée dans un parchemin qui libère 8d6 dégâts de feu.",
    rarity: "rare",
    base: {
      weight: 0.1,
    },
    effects: [itemEffects.fireballLevel3],
    targetingV2: {
      aim: { allowed: ["entity", "position"], required: true, range: 36, lineOfSight: true },
      area: { shape: "circle", radius: 6 },
      affects: { allowed: ["living"], requiresLiving: true },
      defaultPriority: ["nearestEnemy", "farthestPointAhead"],
      suggestedSides: ["enemy"],
    },
    targeting: {
      allowed: ["entity", "position", "free"],
      required: true,
      defaultPriority: ["nearestEnemy", "farthestPointAhead"],
      range: 36,
    },
    modules: {
      item: {},
    },
  },
  {
    id: "tpl_chaos_flask",
    type: "consumable",
    types: ["consumable"],
    tags: ["consumable", "flask", "glass", "chaos", "magic", "alchemy"],
    name: "Flasque chaotique",
    description: "Le liquide change de couleur à chaque battement de cœur.",
    rarity: "uncommon",
    base: {
      weight: 0.3,
    },
    effects: [itemEffects.chaoticDamage3],
    targetingV2: {
      aim: { allowed: ["entity", "position"], required: true, range: 9, lineOfSight: true },
      area: { shape: "circle", radius: 2 },
      affects: { allowed: ["living"], requiresLiving: true },
      defaultPriority: ["nearestEnemy", "farthestPointAhead"],
      suggestedSides: ["enemy"],
    },
    targeting: {
      allowed: ["entity", "position", "free"],
      required: true,
      defaultPriority: ["nearestEnemy", "farthestPointAhead"],
      range: 9,
    },
    modules: {
      item: {},
    },
  },
  {
    id: "tpl_ember_ward",
    type: "garment",
    types: ["accessory"],
    tags: ["accessory", "brooch", "metal", "fire", "protection", "magic"],
    name: "Broche pare-braise",
    description: "Une broche tiède qui avale une partie des flammes.",
    rarity: "uncommon",
    base: {
      weight: 0.05,
    },
    effects: [itemEffects.reduceFire2],
    modules: {
      item: {},
    },
  },
  {
    id: "tpl_alchemical_converter",
    type: "consumable",
    types: ["consumable"],
    tags: ["consumable", "alchemy", "device", "single-use", "craft"],
    name: "Convertisseur alchimique",
    description: "Un petit appareil jetable qui réagit aux pierres magnétiques.",
    rarity: "uncommon",
    base: {
      weight: 0.4,
    },
    effects: [itemEffects.transmuteMagnetStone],
    targeting: {
      allowed: ["item", "free"],
      required: true,
      defaultPriority: ["none"],
    },
    modules: {
      item: {},
    },
  },
  {
    id: "tpl_ember_staff",
    type: "weapon",
    types: ["weapon", "accessory"],
    tags: ["weapon", "staff", "wood", "magic", "fire", "catalyst"],
    name: "Bâton des braises liées",
    description: "Un bâton noirci qui peut frapper comme une arme simple ou libérer des braises concentrées.",
    rarity: "uncommon",
    requiresAttunement: true,
    base: {
      range: 1.5,
      damage: "1d6",
      damageType: "contondant",
      weight: 1.8,
    },
    effects: [itemEffects.grantEmberBolt],
    attacks: [
      {
        id: "strike",
        name: "Coup de bâton",
        label: "Frapper",
        range: 1.5,
        damage: "1d6",
        damageType: "contondant",
        attackKind: "melee",
      },
    ],
    targetingV2: {
      aim: { allowed: ["entity", "position"], required: true, range: 3, lineOfSight: true },
      area: { shape: "none" },
      affects: { allowed: ["living"], maxTargets: 1, requiresLiving: true },
      defaultPriority: ["nearestEnemy"],
      suggestedSides: ["enemy"],
    },
    modules: {
      item: {},
    },
  },
];
